import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
type O={company:string;position:string;location:string;work_mode:string;source:string;source_url:string;description:string;search_term:string}
type Profile={id:string;target_roles?:string[];preferred_locations?:string[];work_modes?:string[];keywords?:string[];preferred_companies?:string[];excluded_companies?:string[];excluded_keywords?:string[];minimum_fit?:number;auto_discovery?:boolean}
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
const targets=[
['NVIDIA','Senior Program Manager','Yokneam','https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Yokneam/Senior-Program-Manager_JR2020294'],
['NVIDIA','Customer Program Manager - Generative AI','Tel Aviv / Raanana / Yokneam','https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Customer-Program-Manager---Generative-AI_JR2017408'],
['Amazon Web Services','Technical Program Manager - Physical Infrastructure, DC Communities','Tel Aviv','https://www.amazon.jobs/en/jobs/10475333/technical-program-manager-physical-infrastructure-dc-communities-dcc-communities'],
['Palo Alto Networks','Principal Technical Program Manager','Tel Aviv','https://jobs.paloaltonetworks.com/en/job/tel-aviv/principal-technical-program-manager/47263/96724737040'],
['Palo Alto Networks','Technical Program Leader - Enterprise SaaS (Idira)','Petah Tikva','https://jobs.paloaltonetworks.com/en/job/petah-tikva/sr-technical-program-manager-idira/47263/96824352080']
] as const
const norm=(s='')=>s.toLocaleLowerCase('he').replace(/[^a-z0-9\u0590-\u05ff]+/gi,' ').trim()
const terms=(p:Profile)=>[...(p.target_roles||[]),...(p.keywords||[]),...(p.preferred_companies||[])].map(norm).filter(Boolean)
const excluded=(p:Profile)=>[...(p.excluded_companies||[]),...(p.excluded_keywords||[])].map(norm).filter(Boolean)
const matchesProfile=(o:O,p:Profile)=>{const text=norm(`${o.company} ${o.position} ${o.location} ${o.description}`);const wanted=terms(p),blocked=excluded(p);if(blocked.some(x=>text.includes(x)))return false;if(!wanted.length)return true;return wanted.some(x=>text.includes(x)||x.split(' ').filter(Boolean).some(w=>w.length>2&&text.includes(w)))}
const fit=(o:O,p:Profile)=>{let n=65,t=norm(o.position+' '+o.description);const wanted=terms(p);for(const k of wanted)if(t.includes(k))n+=7;for(const k of ['program manager','technical program','delivery','customer','software','saas','ai','devops','infrastructure','cross functional','stakeholder','cloud','engineering','מנהל','ניהול','כספים','פיננסי','בנק','בנקאות','חשב','חשבות'])if(t.includes(norm(k)))n+=3;const l=norm(o.location);for(const loc of p.preferred_locations||[])if(l.includes(norm(loc)))n+=5;return Math.min(97,n)}
async function live(o:O){try{const r=await fetch(o.source_url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 JobTrack/4.0'}});if(!r.ok)return null;const html=await r.text();const text=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ');const probe=norm(o.position).split(' ').filter(x=>x.length>3).slice(0,3);if(probe.length&&!probe.every(x=>norm(text).includes(x)))return null;return {...o,description:text.slice(0,5000)}}catch{return null}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const auth=req.headers.get('Authorization')||'';const token=auth.replace(/^Bearer\s+/i,'');const{data:{user}}=await db.auth.getUser(token);if(!user)throw new Error('Authentication required');const{data:profileData,error:profileError}=await db.from('profiles').select('id,target_roles,preferred_locations,work_modes,keywords,preferred_companies,excluded_companies,excluded_keywords,minimum_fit,auto_discovery').eq('id',user.id).single();if(profileError)throw profileError;const profile=profileData as Profile;if(profile.auto_discovery===false)return new Response(JSON.stringify({ok:true,architecture:'profile-driven-multilingual-v4',scanned:0,new_opportunities:0,message:'Auto discovery is disabled'}),{headers:{...cors,'Content-Type':'application/json'}});const searchTerms=terms(profile);const base:O[]=targets.map(x=>({company:x[0],position:x[1],location:x[2],work_mode:'Hybrid / On-site',source:'Company careers',source_url:x[3],description:'',search_term:searchTerms.join(', ')||'Israel jobs'}));const checked=(await Promise.all(base.map(live))).filter(Boolean) as O[];const matched=checked.filter(o=>matchesProfile(o,profile));const [{data:jobs},{data:cands}]=await Promise.all([db.from('jobs').select('company,position,source_url').eq('user_id',user.id),db.from('job_candidates').select('company,position,source_url').eq('user_id',user.id)]);const key=(x:any)=>`${norm(x.company)}|${norm(x.position)}`;const known=new Set([...(jobs||[]),...(cands||[])].map(key));const minimum=profile.minimum_fit??70;const rows=matched.filter(x=>!known.has(key(x))).map(x=>{const score=fit(x,profile);return {...x,user_id:user.id,fit_score:score,priority:score>=90?'High':'Medium',review_status:'New',discovered_at:new Date().toISOString()}}).filter(x=>x.fit_score>=minimum);let inserted:any[]=[];if(rows.length){const r=await db.from('job_candidates').insert(rows).select('id,company,position,fit_score');if(r.error)throw r.error;inserted=r.data||[]}return new Response(JSON.stringify({ok:true,architecture:'profile-driven-multilingual-v4',languages:['en','he'],search_terms:searchTerms,scanned:base.length,live:checked.length,profile_matches:matched.length,new_opportunities:inserted.length,inserted}),{headers:{...cors,'Content-Type':'application/json'}})}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:{...cors,'Content-Type':'application/json'}})}})