import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
type O={company:string;position:string;location:string;work_mode:string;source:string;source_url:string;description:string;search_term:string}
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
const targets=[
['NVIDIA','Senior Program Manager','Yokneam','https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Yokneam/Senior-Program-Manager_JR2020294'],
['NVIDIA','Customer Program Manager - Generative AI','Tel Aviv / Raanana / Yokneam','https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Customer-Program-Manager---Generative-AI_JR2017408'],
['Amazon Web Services','Technical Program Manager - Physical Infrastructure, DC Communities','Tel Aviv','https://www.amazon.jobs/en/jobs/10475333/technical-program-manager-physical-infrastructure-dc-communities-dcc-communities'],
['Palo Alto Networks','Principal Technical Program Manager','Tel Aviv','https://jobs.paloaltonetworks.com/en/job/tel-aviv/principal-technical-program-manager/47263/96724737040'],
['Palo Alto Networks','Technical Program Leader - Enterprise SaaS (Idira)','Petah Tikva','https://jobs.paloaltonetworks.com/en/job/petah-tikva/sr-technical-program-manager-idira/47263/96824352080']
] as const
const norm=(s='')=>s.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
const fit=(o:O)=>{let n=70,t=norm(o.position+' '+o.description);for(const k of ['program manager','technical program','delivery','customer','software','saas','ai','devops','infrastructure','cross functional','stakeholder','cloud','engineering'])if(t.includes(k))n+=3;const l=norm(o.location);if(['yokneam','haifa','netanya','raanana','tel aviv','petah tikva'].some(x=>l.includes(x)))n+=3;return Math.min(97,n)}
async function live(o:O){try{const r=await fetch(o.source_url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 JobTrack/3.0'}});if(!r.ok)return null;const html=await r.text();const text=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ');const probe=norm(o.position).split(' ').filter(x=>x.length>3).slice(0,3);if(probe.length&&!probe.every(x=>norm(text).includes(x)))return null;return {...o,description:text.slice(0,5000)}}catch{return null}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const base:O[]=targets.map(x=>({company:x[0],position:x[1],location:x[2],work_mode:'Hybrid / On-site',source:'Company careers',source_url:x[3],description:'',search_term:'Israel Program/Delivery/Technical Program Manager'}));const checked=(await Promise.all(base.map(live))).filter(Boolean) as O[];const [{data:jobs},{data:cands}]=await Promise.all([db.from('jobs').select('company,position,source_url'),db.from('job_candidates').select('company,position,source_url')]);const key=(x:any)=>`${norm(x.company)}|${norm(x.position)}`;const known=new Set([...(jobs||[]),...(cands||[])].map(key));const rows=checked.filter(x=>!known.has(key(x))).map(x=>{const score=fit(x);return {...x,fit_score:score,priority:score>=90?'High':'Medium',review_status:'New',discovered_at:new Date().toISOString()}});let inserted:any[]=[];if(rows.length){const r=await db.from('job_candidates').insert(rows).select('id,company,position,fit_score');if(r.error)throw r.error;inserted=r.data||[]}return new Response(JSON.stringify({ok:true,architecture:'israel-multisource-company-careers-v3',scanned:base.length,live:checked.length,duplicates:checked.length-rows.length,new_opportunities:inserted.length,inserted,sources:[...new Set(base.map(x=>x.company))]}),{headers:{...cors,'Content-Type':'application/json'}})}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:{...cors,'Content-Type':'application/json'}})}})