import { ExternalLink } from 'lucide-react'

const BulletList=({items}:{items:string[]})=><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-700">{items.map(x=><li key={x}>{x}</li>)}</ul>
const Tags=({items}:{items:string[]})=><div className="mt-3 flex flex-wrap gap-2">{items.map(x=><span key={x} className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{x}</span>)}</div>

export default function CVPage(){
 const modern=['Technical Program Management','R&D Delivery','AI / Computer Vision','AWS SaaS & IoT','DevOps & CI/CD','Cross-functional Leadership','Release Management','Production Observability','Hardware / Software Integration','Customer Delivery']
 const tools=['AWS','AWS IoT Core','Azure DevOps','Jira','Confluence','Datadog','Port','Draft','CI/CD','Agile / Scrum','Java','J2EE','Oracle','SQL']
 return <>
  <div className="rounded-2xl bg-slate-950 p-6 text-white shadow-sm">
   <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-indigo-300">Curriculum Vitae</p><h1 className="mt-1 text-3xl font-bold">Oren Tanhum</h1><p className="mt-2 text-lg text-slate-200">Technical Program Manager | R&D Delivery | SaaS, AI & IoT | Cloud & DevOps</p></div><div className="text-sm text-slate-300"><p>052-396-6982</p><p>orentanhum@gmail.com</p><a className="text-indigo-300" href="https://www.linkedin.com/in/oren-tanhum-9331b54" target="_blank">LinkedIn <ExternalLink className="inline" size={12}/></a></div></div>
  </div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[2fr_1fr]">
   <section className="space-y-4">
    <div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Executive Profile</h2><p className="mt-2 text-sm leading-6 text-slate-700">Senior Technical Program and R&D Delivery leader with 27+ years of experience leading complex software organizations, multidisciplinary product development and customer-facing delivery. Currently managing large-scale animal health technology programs at MSD Animal Health, delivering real-time monitoring solutions that combine AWS cloud/SaaS, IoT, hardware, AI and computer vision. Experienced in driving end-to-end delivery across Software, Hardware, Data, AI, Product, QA and Platform/DevOps teams. Strong background in Agile delivery, DevOps, CI/CD, release management, production observability and engineering governance. Previously led R&D and Professional Services organizations and international Telecom/SaaS programs for customers including Pelephone, IEC, Moldtelecom, NTT DOCOMO and Vodafone.</p></div>
    <div className="rounded-xl border-2 border-indigo-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-600">Current Experience</p><h2 className="text-xl font-bold">MSD Animal Health Technology Labs</h2><p className="font-semibold text-slate-700">Technical Program Manager</p></div><p className="text-sm text-slate-500">Sep 2024 – Present · Israel · Hybrid</p></div><BulletList items={[
     'Lead development and delivery of large-scale, multidisciplinary real-time animal health monitoring products combining cloud software, IoT, hardware and AI technologies.',
     'Drive end-to-end technical program delivery across Software Engineering, Hardware, AI/Computer Vision, Data, QA, Product and Platform/DevOps teams.',
     'Manage complex AWS-based SaaS and IoT solutions, including AWS IoT Core, hardware integrations, cloud services and real-time monitoring capabilities.',
     'Coordinate AI and computer-vision capabilities, aligning algorithm development with software, hardware, data and product roadmaps.',
     'Own program planning, prioritization, dependency and risk management, delivery tracking and stakeholder communication across multiple engineering teams.',
     'Drive Agile and DevOps delivery practices, improving CI/CD, release governance, deployment traceability and rollback readiness.',
     'Use Azure DevOps and Jira for backlog management, delivery planning, sprint/release tracking, engineering workflows and cross-team execution.',
     'Use Datadog for production monitoring and observability, supporting data-driven analysis of application behavior, service performance and production issues.',
     'Improve engineering transparency and knowledge management with Confluence, Port and Draft, supporting documentation, developer experience, service ownership and engineering standards.'
    ]}/></div>
    <div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">MIND CTI · Leadership & Delivery</h2><div className="mt-4 space-y-5 text-sm text-slate-700"><div><h3 className="font-bold text-slate-900">VP Professional Services · Sep 2016 – Dec 2024</h3><BulletList items={['Led Project Management, customer delivery, operations and support for major telecom and enterprise customers.','Direct program/project leadership for Pelephone/Rami Levy, IEC/Ericsson smart metering, EastLink, Ukrtelecom and Chat Mobility.','Managed delivery against schedule, quality and budget; led Project Managers and Support organization.','Raised customer ticket satisfaction survey index to 98.54%.']}/></div><div><h3 className="font-bold text-slate-900">Director, R&D Manager & Project Management · Mar 2012 – Aug 2016</h3><BulletList items={['Led end-to-end programs from RFP through planning, development, integration and customer-site deployment.','Managed work plans, pricing, budgets, quality, major changes and critical production issues across onshore/offshore matrix teams.','Worked with Waterfall and Agile/Scrum delivery methodologies.']}/></div><div><h3 className="font-bold text-slate-900">MINDbill Development Director · Nov 2006 – Mar 2012</h3><BulletList items={['Managed an R&D organization of approximately 180 developers and testers across Israel and Romania.','Led multiple parallel Web/J2EE telecom software programs, system integration, R&D methodology, recruitment and training.','Defined and deployed development methodologies including Waterfall and Agile/Scrum in an ISO 9001 environment.']}/></div><div><h3 className="font-bold text-slate-900">Earlier MIND CTI Engineering Leadership · 1999 – 2006</h3><p className="mt-1 leading-6">Finance Group Leader and Finance Team Leader. Managed development teams in Israel and Romania while remaining close to architecture, design and hands-on software development in Java, C++, Delphi and Oracle.</p></div></div></div>
   </section>
   <aside className="space-y-4">
    <div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Core Expertise</h2><Tags items={modern}/></div>
    <div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Technology & Tools</h2><Tags items={tools}/></div>
    <div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Career Highlights</h2><BulletList items={['27+ years across R&D, Professional Services and technical delivery','Managed R&D organization of ~180 developers and testers','International telecom and enterprise customer delivery','Deep software development and system-integration foundation','Current leadership across AI, IoT, SaaS, hardware and DevOps']}/></div>
    <div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Education</h2><p className="mt-2 text-sm"><b>University of Haifa</b><br/>B.A. Mathematics & Computer Science<br/>1994–1997</p></div>
    <div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Languages</h2><p className="mt-2 text-sm">Hebrew — Native</p><p className="text-sm">English — Fluent</p></div>
    <div className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Professional Development</h2><p className="mt-2 text-sm leading-6 text-slate-700">Project Management · Management · Agile/Scrum · DBA · J2EE · Java Design Patterns</p></div>
   </aside>
  </div>
 </>
}
