export const developmentPlanSections = [
{title:'What the market requires',body:'Across 15 Israel-based program/project manager postings, delivery craft is universal (15/15). Executive influence without authority appears in 14/15, communication/autonomy in 13/15, cross-org programs in 12/15, and risk/dependency mechanics in 11/15. Technical depth and industry domain each appear in 10/15. The strongest differentiators are process design/adoption (8/15), PM tooling/automation (6/15), self-serve data/KPIs (6/15), money ownership (6/15), customer-facing delivery (6/15), and AI in the workflow (5/15).'},
{title:'Priority 1 — Get a cost line',body:'Ask for ownership of one real cost line: vendor/subcontractor spend, cloud cost, or effort-to-cost. Build cost-versus-plan into the delivery dashboard, then record the first variance and the decision you made because of it. Evidence target: a work-breakdown-to-budget example plus one variance decision.'},
{title:'Priority 2 — Build a written operating model',body:'Document definition of ready/done, dependency handling, escalation path, release go/no-go and review flows. Instrument adoption from day one and review the model quarterly. Evidence target: before/after process description plus adoption data.'},
{title:'Priority 3 — Commitment management',body:'Move beyond status reporting. Add say-do ratio, forecast-versus-actual, cycle time and escaped-defect trends. Publish forecasts with confidence ranges and report how they landed. Evidence target: a predictability trend and a case where you flagged a forecast miss early.'},
{title:'Priority 4 — Executive influence',body:'Drive one contested issue to a written decision in a forum you do not own. Use a one-page format: options, data, recommendation and risks. Preserve the disagreement and the final decision. Executive influence is requested in 14 of 15 roles.'},
{title:'Priority 5 — Customer-facing delivery',body:'Run a delivery review directly with an external customer and own one escalation end to end. Evidence target: a commitment you had to renegotiate and how you maintained the relationship.'},
{title:'Priority 6 — Release & environment ownership',body:'Own go/no-go, cutover and rollback for a release. Get closer to pipelines, environments, monitoring, networking, storage, databases and cloud cost. Evidence target: a release decision plus one incident or rollback you ran.'},
{title:'Sequencing',body:'Next 30 days: draft the delivery playbook, publish commitment reliability weekly, ask for a cost line. Next 90 days: drive a contested decision, run cost-versus-plan with a variance decision, attach adoption numbers to the playbook. Next 6 months: own an external customer delivery review, own release go/no-go, and keep the evidence log current.'},
{title:'Program Manager vs Delivery Manager',body:'Delivery Manager asks: will it ship when promised at the quality promised? It owns predictability, throughput, release readiness, team health and customer commitment. Program Manager asks: will the cross-org outcome actually happen? It owns dependencies, executive forums and the operating model. Commitment management is the Delivery Manager core; executive influence is the Program Manager core.'},
{title:'De-prioritize for now',body:'Do not over-invest in PMP/CAPM (only 2/15 postings and both as a plus), Cloud FinOps as a standalone skill (1/15), or more basic risk/status-reporting craft. NPI, supply-chain and hardware depth are worthwhile only if you deliberately target the hardware cluster.'}
]
