export const roleLibraryJobs = [
{company:'AT&T',position:'Program Manager Lead',location:'Center District, Israel',work_mode:'Hybrid',source_url:'https://www.linkedin.com/jobs/view/4444893140',source:'LinkedIn',fit_score:91},
{company:'Amphenol',position:'Technical Program Manager — High-Speed Cable Assembly & Connectivity',location:'Petah Tikva, Center District, Israel',work_mode:'Hybrid',source_url:'https://www.linkedin.com/jobs/view/4441820810',source:'LinkedIn',fit_score:84},
{company:'Cadence',position:'Project / Program Manager — Cadence Services',location:'Petah Tikva, Center District, Israel',work_mode:'Hybrid',source_url:'https://www.linkedin.com/jobs/view/4405976301',source:'LinkedIn',fit_score:90},
{company:'Cisco',position:'Senior Software Program Manager',location:'Caesarea, Haifa District, Israel',work_mode:'Hybrid',source_url:'https://www.linkedin.com/jobs/view/4440527451',source:'LinkedIn',fit_score:95},
{company:'TBD',position:'Technical Project Manager — Cloud Infrastructure (12-month contract)',location:'Israel',work_mode:'Remote',source_url:'',source:'Other',fit_score:88},
{company:'Elbit Systems',position:'Program Manager — Network Warfare Business Line',location:'Netanya',work_mode:'Hybrid',source_url:'https://elbitsystemscareer.com/job/?jid=19571',source:'Company Website',fit_score:86},
{company:'Electreon',position:'Program Manager',location:'Beit Yanai, Center District, Israel',work_mode:'On-site',source_url:'https://www.linkedin.com/jobs/view/4439849632',source:'LinkedIn',fit_score:82},
{company:'Harmonic',position:'Sr. Technical Program/Project Manager',location:'Caesarea, Haifa District, Israel',work_mode:'Hybrid',source_url:'https://www.linkedin.com/jobs/view/4451410307',source:'LinkedIn',fit_score:96},
{company:'Majestic Labs',position:'Technical Program Manager',location:"Ra'anana, Center District, Israel",work_mode:'Hybrid',source_url:'https://www.linkedin.com/jobs/view/4438980890',source:'LinkedIn',fit_score:89},
{company:'MicroCon Vision Ltd.',position:'Technical Project Manager',location:'Kfar Saba, Center District, Israel',work_mode:'Hybrid',source_url:'https://www.linkedin.com/jobs/view/4451556387',source:'LinkedIn',fit_score:83},
{company:'NiCE',position:'Lead Program Manager',location:"Ra'anana, Center District, Israel",work_mode:'Hybrid',source_url:'https://www.linkedin.com/jobs/view/4435601071',source:'LinkedIn',fit_score:94},
{company:'Palo Alto Networks',position:'Technical Program Leader — Enterprise SaaS (Idira)',location:'Petah Tikva, Center District, Israel',work_mode:'On-site',source_url:'https://www.linkedin.com/jobs/view/4432278453',source:'LinkedIn',fit_score:97},
{company:'Playtika',position:'Tech Program Manager — TechOps & IT Division',location:'Herzliya, Tel Aviv District, Israel',work_mode:'Hybrid',source_url:'https://www.linkedin.com/jobs/view/4421941159',source:'LinkedIn',fit_score:92},
{company:'Redler Technologies',position:'Senior Project Manager',location:'Kfar Saba, Center District, Israel',work_mode:'On-site',source_url:'https://www.linkedin.com/jobs/view/4449514331',source:'LinkedIn',fit_score:80},
{company:'Shabak (Israeli Security Agency)',position:'Program Manager — IT Infrastructure (ref 2623)',location:'Merkaz — Central Israel',work_mode:'Hybrid',source_url:'https://il.linkedin.com/jobs/view/program-manager-it-infrastructure-2623-at-shabak-israeli-security-agency-career-4431202418',source:'LinkedIn',fit_score:87}
].map(j=>({...j,priority:j.fit_score>=93?'High':j.fit_score>=85?'Medium':'Low',status:'Interested',next_action:j.fit_score>=93?'High fit — review and apply':'Review fit and decide whether to apply',description:'Fit score estimated against Oren’s Program / Delivery Manager profile using role title, domain, seniority, technology alignment and location/work-mode. Re-score when full job description is available.'}))
